### ISSUE TITLE
Settings Crash

### ISSUE THREAD

**Issue by eli876** [hardpixel/dark-variant#2]
If an app is uninstalled while its pref is set to dark mode, settings no longer opens:
JS ERROR: Failed to open preferences: TypeError: appInfo is null
                                    _init@/home/eli/.local/share/gnome-shell/extensions/dark-variant@hardpixel.eu/prefs.js:111:9
                                    _onSync/<@/home/eli/.local/share/gnome-shell/extensions/dark-variant@hardpixel.eu/prefs.js:76:29
                                    _onSync@/home/eli/.local/share/gnome-shell/extensions/dark-variant@hardpixel.eu/prefs.js:73:15
                                    _init@/home/eli/.local/share/gnome-shell/extensions/dark-variant@hardpixel.eu/prefs.js:59:12
                                    buildPrefsWidget@/home/eli/.local/share/gnome-shell/extensions/dark-variant@hardpixel.eu/prefs.js:236:18
                                    _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
                                    OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
                                    asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
                                    run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
                                    main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
lines 1-22

Also: 
JS ERROR: Failed to open preferences: Error: Type name Gjs_DarkVariantPrefsWidget is already registered
                                  _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:444:27
                                  _init/Gtk.Widget._classInit@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:74:32
                                  registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:78:22
                                  @/home/eli/.local/share/gnome-shell/extensions/dark-variant@hardpixel.eu/prefs.js:8:35
                                  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:206:33
                                  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
                                  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
                                  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
                                  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
                                  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
                                  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
                                  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by jonian** [comment]
Hi @eli876, thanks for the report. I have fixed the issue and released a new version.

**Comment by eli876** [comment]
Awesome! Thank!s!
